### ISSUE TITLE
Fan2Para: Wrong arcsin check

### ISSUE THREAD

**Issue by j-stephan** [HZDR-FWDF/RISA#16]
In Fan2Para.cu:347 we are checking if we can apply the arcsin:

```
if (temp_1 <= 1 || temp_1 >= -1)
```

This evaluates to ``true`` for ``temp_1 = 2``:

```
if(2 <= 1 || 2 >= -1)

if(false || true)

if(true)
```

**Comment by tobiasfrust** [comment]
So, it should be:

`if (temp_1 <= 1 && temp_1 >= -1)`

Am I right?

**Comment by BieberleA** [comment]
I check together with Micha.

**Comment by BieberleA** [comment]
Hi Dominic, that bug needs also to be fixed in the GPU - Toolkit.

**Comment by j-stephan** [comment]
@tobiasfrust: Yep.
